import { makeStyles } from "@mui/styles";
const useStyles = makeStyles({
  chatbot: {
    fontFamily: "Segoe UI Emoji",
    borderRadius: "10px",
    boxShadow: "0 12px 24px 0 rgba(0, 0, 0, 0.15)",
    background: "#f5f8fb",
    align: "center",
    display: "flex",
    flexDirection: "column",
    width: "500px",
    overflow: "hidden",
  },
  header: {
    padding: "20px",
    align: "center",
    color: "rgb(255, 255, 255)",
    maxHeight: "58px",
    fontSize: "16px",
    fontWeight: "bold",
    background: "#002f50",
  },
  messages: {
    width: "100%",
    height: "400px",
    overflow: "auto",
    display: "flex",
    flexDirection: "column",
    padding: "10px 0px",
  },
  messageContainer: {
    width: "100%",
  },
  botMessage: {
    float: "left",
    padding: "15px 20px",
    margin: "5px",
    borderRadius: "20px 20px 20px 1px",
    background: "#00aaa5",
    color: "white",
    minWidth: "40px",
  },
  input: {
    position: "relative",
  },
  userMessage: {
    float: "right",
    padding: "15px 10px",
    margin: "10px",
    borderRadius: "20px 20px 1px 20px",
    background: "#cccccc",
    color: "black",
  },
  formButton: {
    background: "transparent",
    border: 0,
    borderBottomRightRadius: "10px",
    boxShadow: "none",
    cursor: "pointer",
    fill: "#4a4a4a",
    opacity: 1,
    outline: "none",
    padding: "14px 16px 12px 16px",
    position: "absolute",
    right: 0,
    top: 0,
  },
  formInput: {
    fontFamily: "Segoe UI Emoji",
    fontSize: "16px",
    border: 0,
    borderRadius: 0,
    borderBottomLeftRadius: "10px",
    borderBottomRightRadius: "10px",
    borderTop: "1px solid #eee",
    boxShadow: "none",
    boxSizing: "border-box",
    opacity: 1,
    outline: "none",
    padding: "16px 52px 16px 10px",
    width: "100%",
  },
  formInputFocus: {
    outline: "none",
  },
});
export default useStyles;
